/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERATION_H_RPCGEN
#define _OPERATION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STRING 16

struct Dato {
	char *contenuto;
};
typedef struct Dato Dato;

#define OPERATION 0x20000020
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET 1
extern  Dato * get_1(void *, CLIENT *);
extern  Dato * get_1_svc(void *, struct svc_req *);
#define SET 2
extern  int * set_1(Dato *, CLIENT *);
extern  int * set_1_svc(Dato *, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET 1
extern  Dato * get_1();
extern  Dato * get_1_svc();
#define SET 2
extern  int * set_1();
extern  int * set_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Dato (XDR *, Dato*);

#else /* K&R C */
extern bool_t xdr_Dato ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERATION_H_RPCGEN */
