/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFILE_H_RPCGEN
#define _XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define K 10
#define MAX_STRING 128

struct Licenza {
	char *targa;
	char *patente;
};
typedef struct Licenza Licenza;

struct Prenotazione {
	char *targa;
	char *patente;
	char *tipo;
	char *immagini;
};
typedef struct Prenotazione Prenotazione;

struct Prenotazioni {
	Prenotazione list[K];
	int numero;
};
typedef struct Prenotazioni Prenotazioni;

#define OPERATION 0x20000020
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VISUALIZZA 1
extern  Prenotazioni * visualizza_1(char **, CLIENT *);
extern  Prenotazioni * visualizza_1_svc(char **, struct svc_req *);
#define AGGIORNA 2
extern  int * aggiorna_1(Licenza *, CLIENT *);
extern  int * aggiorna_1_svc(Licenza *, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VISUALIZZA 1
extern  Prenotazioni * visualizza_1();
extern  Prenotazioni * visualizza_1_svc();
#define AGGIORNA 2
extern  int * aggiorna_1();
extern  int * aggiorna_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Licenza (XDR *, Licenza*);
extern  bool_t xdr_Prenotazione (XDR *, Prenotazione*);
extern  bool_t xdr_Prenotazioni (XDR *, Prenotazioni*);

#else /* K&R C */
extern bool_t xdr_Licenza ();
extern bool_t xdr_Prenotazione ();
extern bool_t xdr_Prenotazioni ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XFILE_H_RPCGEN */
