/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ESAME_140711_H_RPCGEN
#define _ESAME_140711_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define LUNGHEZZA_NOME 30
#define LUNGHEZZA_NOME_FILE 30
#define LUNGHEZZA_PAROLA 30
#define NUM_PAROLE 2

struct Parola {
	char parola[LUNGHEZZA_PAROLA];
};
typedef struct Parola Parola;

struct RigaRicerca {
	char nome[LUNGHEZZA_NOME];
	int durata;
	Parola p[NUM_PAROLE];
};
typedef struct RigaRicerca RigaRicerca;

struct Tabella {
	RigaRicerca candidato[8];
};
typedef struct Tabella Tabella;

struct Candidato {
	char nome[LUNGHEZZA_NOME];
	char nomeFile[LUNGHEZZA_NOME_FILE];
	int durata;
	Parola p[NUM_PAROLE];
};
typedef struct Candidato Candidato;

struct Periodo {
	char dataIniziale[11];
	char dataFinale[11];
};
typedef struct Periodo Periodo;

struct CandidatoParola {
	char nome[LUNGHEZZA_NOME];
	Parola p;
};
typedef struct CandidatoParola CandidatoParola;

#define PROVINIPROG 0x20000013
#define PROVINIVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ricerca_provini 1
extern  Tabella * ricerca_provini_1(Periodo *, CLIENT *);
extern  Tabella * ricerca_provini_1_svc(Periodo *, struct svc_req *);
#define aggiungi_parola 2
extern  int * aggiungi_parola_1(CandidatoParola *, CLIENT *);
extern  int * aggiungi_parola_1_svc(CandidatoParola *, struct svc_req *);
extern int proviniprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ricerca_provini 1
extern  Tabella * ricerca_provini_1();
extern  Tabella * ricerca_provini_1_svc();
#define aggiungi_parola 2
extern  int * aggiungi_parola_1();
extern  int * aggiungi_parola_1_svc();
extern int proviniprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Parola (XDR *, Parola*);
extern  bool_t xdr_RigaRicerca (XDR *, RigaRicerca*);
extern  bool_t xdr_Tabella (XDR *, Tabella*);
extern  bool_t xdr_Candidato (XDR *, Candidato*);
extern  bool_t xdr_Periodo (XDR *, Periodo*);
extern  bool_t xdr_CandidatoParola (XDR *, CandidatoParola*);

#else /* K&R C */
extern bool_t xdr_Parola ();
extern bool_t xdr_RigaRicerca ();
extern bool_t xdr_Tabella ();
extern bool_t xdr_Candidato ();
extern bool_t xdr_Periodo ();
extern bool_t xdr_CandidatoParola ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ESAME_140711_H_RPCGEN */
