/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operazioni.h"

bool_t
xdr_RigaRicerca (XDR *xdrs, RigaRicerca *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, LUNGHEZZA_NOME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->durata))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->p, NUM_PAROLE,
		sizeof (Parola), (xdrproc_t) xdr_Parola))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Tabella (XDR *xdrs, Tabella *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->candidato, 8,
		sizeof (RigaRicerca), (xdrproc_t) xdr_RigaRicerca))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Candidato (XDR *xdrs, Candidato *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, LUNGHEZZA_NOME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nomeFile, LUNGHEZZA_NOME_FILE,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->durata))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->p, NUM_PAROLE,
		sizeof (Parola), (xdrproc_t) xdr_Parola))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Parola (XDR *xdrs, Parola *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->parola, LUNGHEZZA_PAROLA,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Periodo (XDR *xdrs, Periodo *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->dataIniziale, 8,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->dataFinale, 8,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CandidatoParola (XDR *xdrs, CandidatoParola *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nomeCandidato, LUNGHEZZA_NOME,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_Parola (xdrs, &objp->p))
		 return FALSE;
	return TRUE;
}
