/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STRING 256
#define N 6

struct Input {
	char *nomeDir;
	char carattere;
	int numOccorrenze;
};
typedef struct Input Input;

struct NomeFile {
	char *nomeFile;
};
typedef struct NomeFile NomeFile;

struct Output {
	NomeFile listaNomeFile[N];
	int indice;
	int esito;
};
typedef struct Output Output;

#define RPCESAME 0x20000020
#define RPCESAMEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define lista_file_carattere 1
extern  Output * lista_file_carattere_1(Input *, CLIENT *);
extern  Output * lista_file_carattere_1_svc(Input *, struct svc_req *);
#define elimina_occorrenze 2
extern  int * elimina_occorrenze_1(char **, CLIENT *);
extern  int * elimina_occorrenze_1_svc(char **, struct svc_req *);
extern int rpcesame_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define lista_file_carattere 1
extern  Output * lista_file_carattere_1();
extern  Output * lista_file_carattere_1_svc();
#define elimina_occorrenze 2
extern  int * elimina_occorrenze_1();
extern  int * elimina_occorrenze_1_svc();
extern int rpcesame_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_NomeFile (XDR *, NomeFile*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_NomeFile ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
