/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERAZIONI_H_RPCGEN
#define _OPERAZIONI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Giudici {
	char *giudice;
	int voto;
};
typedef struct Giudici Giudici;

struct Candidato {
	char *nomeCandidato;
	char *nomeGiudice;
	char categoria;
	char *nomeFile;
	char fase;
	int voto;
};
typedef struct Candidato Candidato;

struct CandidatoVoto {
	char *nome;
	char tipoOperazione;
};
typedef struct CandidatoVoto CandidatoVoto;

#define OPERAZIONIPROG 0x20000013
#define OPERAZIONIVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define classifica_giudici 1
extern  Giudici * classifica_giudici_1(void *, CLIENT *);
extern  Giudici * classifica_giudici_1_svc(void *, struct svc_req *);
#define esprimi_voto 2
extern  int * esprimi_voto_1(CandidatoVoto *, CLIENT *);
extern  int * esprimi_voto_1_svc(CandidatoVoto *, struct svc_req *);
extern int operazioniprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define classifica_giudici 1
extern  Giudici * classifica_giudici_1();
extern  Giudici * classifica_giudici_1_svc();
#define esprimi_voto 2
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
extern int operazioniprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Giudici (XDR *, Giudici*);
extern  bool_t xdr_Candidato (XDR *, Candidato*);
extern  bool_t xdr_CandidatoVoto (XDR *, CandidatoVoto*);

#else /* K&R C */
extern bool_t xdr_Giudici ();
extern bool_t xdr_Candidato ();
extern bool_t xdr_CandidatoVoto ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERAZIONI_H_RPCGEN */
