/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operazioni.h"

bool_t
xdr_Giudici (XDR *xdrs, Giudici *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->giudice, 30))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->voto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CandidatoVoto (XDR *xdrs, CandidatoVoto *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nome, 30))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->tipoOperazione, 1))
		 return FALSE;
	return TRUE;
}
