/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERAZIONI_H_RPCGEN
#define _OPERAZIONI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Wc {
	int righe;
	int caratteri;
	int parole;
};
typedef struct Wc Wc;

struct NameSize {
	char *nome;
	int dim;
};
typedef struct NameSize NameSize;

#define OPERAZIONIPROG 0x20000013
#define OPERAZIONIVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define file_scan 1
extern  Wc * file_scan_1(char **, CLIENT *);
extern  Wc * file_scan_1_svc(char **, struct svc_req *);
#define dir_scan 2
extern  int * dir_scan_1(NameSize *, CLIENT *);
extern  int * dir_scan_1_svc(NameSize *, struct svc_req *);
extern int operazioniprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define file_scan 1
extern  Wc * file_scan_1();
extern  Wc * file_scan_1_svc();
#define dir_scan 2
extern  int * dir_scan_1();
extern  int * dir_scan_1_svc();
extern int operazioniprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Wc (XDR *, Wc*);
extern  bool_t xdr_NameSize (XDR *, NameSize*);

#else /* K&R C */
extern bool_t xdr_Wc ();
extern bool_t xdr_NameSize ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERAZIONI_H_RPCGEN */
