/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operazioni.h"

bool_t
xdr_Wc (XDR *xdrs, Wc *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->righe))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->caratteri))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->parole))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_NameSize (XDR *xdrs, NameSize *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nome, 20))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dim))
		 return FALSE;
	return TRUE;
}
