/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "xFile.h"

bool_t
xdr_Ritardo (XDR *xdrs, Ritardo *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, MAX_STRING))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rit))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Corsa (XDR *xdrs, Corsa *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_string (xdrs, &objp->id, MAX_STRING))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->par, MAX_STRING))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->arr, MAX_STRING))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->hh))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mm))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->rit))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->hh);
		IXDR_PUT_LONG(buf, objp->mm);
		IXDR_PUT_LONG(buf, objp->rit);
		}
		 if (!xdr_string (xdrs, &objp->aud, MAX_STRING))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_string (xdrs, &objp->id, MAX_STRING))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->par, MAX_STRING))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->arr, MAX_STRING))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->hh))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mm))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->rit))
				 return FALSE;

		} else {
		objp->hh = IXDR_GET_LONG(buf);
		objp->mm = IXDR_GET_LONG(buf);
		objp->rit = IXDR_GET_LONG(buf);
		}
		 if (!xdr_string (xdrs, &objp->aud, MAX_STRING))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_string (xdrs, &objp->id, MAX_STRING))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->par, MAX_STRING))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arr, MAX_STRING))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->hh))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mm))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rit))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->aud, MAX_STRING))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Corse (XDR *xdrs, Corse *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->list, K,
		sizeof (Corsa), (xdrproc_t) xdr_Corsa))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numero))
		 return FALSE;
	return TRUE;
}
