/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XFILE_H_RPCGEN
#define _XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define K 6
#define MAX_STRING 128

struct Ritardo {
	char *id;
	int rit;
};
typedef struct Ritardo Ritardo;

struct Corsa {
	char *id;
	char *par;
	char *arr;
	int hh;
	int mm;
	int rit;
	char *aud;
};
typedef struct Corsa Corsa;

struct Corse {
	Corsa list[K];
	int numero;
};
typedef struct Corse Corse;

#define OPERATION 0x20000020
#define OPERATIONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define VISUALIZZA 1
extern  Corse * visualizza_1(char **, CLIENT *);
extern  Corse * visualizza_1_svc(char **, struct svc_req *);
#define MODIFICA 2
extern  int * modifica_1(Ritardo *, CLIENT *);
extern  int * modifica_1_svc(Ritardo *, struct svc_req *);
extern int operation_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VISUALIZZA 1
extern  Corse * visualizza_1();
extern  Corse * visualizza_1_svc();
#define MODIFICA 2
extern  int * modifica_1();
extern  int * modifica_1_svc();
extern int operation_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Ritardo (XDR *, Ritardo*);
extern  bool_t xdr_Corsa (XDR *, Corsa*);
extern  bool_t xdr_Corse (XDR *, Corse*);

#else /* K&R C */
extern bool_t xdr_Ritardo ();
extern bool_t xdr_Corsa ();
extern bool_t xdr_Corse ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XFILE_H_RPCGEN */
