/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_STRING 256
#define DATA_LENGTH 11

struct Evento {
	char *id;
	char *tipo;
	char *data;
	char *luogo;
	int bigliettiDisponibili;
	int prezzo;
};
typedef struct Evento Evento;

struct Input {
	char *id;
	int numBigliettiDaAcquistare;
};
typedef struct Input Input;

#define RPCESAME 0x20000020
#define RPCESAMEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define inserimento_evento 1
extern  int * inserimento_evento_1(Evento *, CLIENT *);
extern  int * inserimento_evento_1_svc(Evento *, struct svc_req *);
#define acquista_biglietti 2
extern  int * acquista_biglietti_1(Input *, CLIENT *);
extern  int * acquista_biglietti_1_svc(Input *, struct svc_req *);
extern int rpcesame_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define inserimento_evento 1
extern  int * inserimento_evento_1();
extern  int * inserimento_evento_1_svc();
#define acquista_biglietti 2
extern  int * acquista_biglietti_1();
extern  int * acquista_biglietti_1_svc();
extern int rpcesame_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Evento (XDR *, Evento*);
extern  bool_t xdr_Input (XDR *, Input*);

#else /* K&R C */
extern bool_t xdr_Evento ();
extern bool_t xdr_Input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
